"""Create pages, terms, postings tables

Revision ID: ed5433c9309a
Revises: 
Create Date: 2026-07-22 15:04:44.760082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5433c9309a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_url'), 'pages', ['url'], unique=True)
    op.create_table('terms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('term', sa.String(length=128), nullable=False),
    sa.Column('document_frequency', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_term'), 'terms', ['term'], unique=True)
    op.create_table('postings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('term_frequency', sa.Integer(), nullable=False),
    sa.Column('tfidf_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'page_id', name='uq_term_page')
    )
    op.create_index(op.f('ix_postings_page_id'), 'postings', ['page_id'], unique=False)
    op.create_index(op.f('ix_postings_term_id'), 'postings', ['term_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postings_term_id'), table_name='postings')
    op.drop_index(op.f('ix_postings_page_id'), table_name='postings')
    op.drop_table('postings')
    op.drop_index(op.f('ix_terms_term'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_pages_url'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
